durin = read.csv("clean_data/durin_clean.csv")

source("R code/functions/get_summary_stats_precise.R")

# Plant means -----
## Calculate based on age group ----
trait.avg = function(data, leaf.age) {
  data |>
  # Filter to just my species
  filter(species %in% c("Empetrum nigrum", "Vaccinium vitis-idaea")) |>
  # Filter to just Sogndal
  filter(siteID == "Sogndal") |>
  # Traits only
  filter(project == "Field - Traits") |>
  # Leaf age
  filter(leaf_age == leaf.age) |>
  # Assign indivdual plant numbers
  mutate(
    # Temp code to replace missing plot nr
    DURIN_plot = replace_na(DURIN_plot, "SO_F_EN_1"),
    plantID.unique = paste0(DURIN_plot, "_plant", plant_nr)) |>
  # Tidy in long form
  select(species, habitat, DURIN_plot, plantID.unique, leaf_age, leaf_thickness_1_mm, leaf_thickness_2_mm, leaf_thickness_3_mm,
         wet_mass_g:LDMC) |>
  relocate(c(dry_mass_g, wet_mass_g, leaf_area, SLA, LDMC, leaf_thickness_1_mm:leaf_thickness_3_mm),
           .after = leaf_age) |>
  pivot_longer(cols = dry_mass_g:leaf_thickness_3_mm, names_to = "trait", values_to = "value") |>
  # Standardize traits
  mutate(trait = replace(trait,
                         trait == "leaf_thickness_1_mm" | trait == "leaf_thickness_2_mm" | trait == "leaf_thickness_3_mm",
                         "leaf_thickness")) |>
  # Remove NAs generated by errors
  drop_na(value) |>
  # Calculate averages
  group_by(DURIN_plot, species, habitat, plantID.unique, leaf_age, trait) |>
  # get_summary_stats_precise(type = "mean") |>
  summarise_all(list(~mean(.),~sd(.),
                ~list(c(summary(.))))) %>% unnest_wider(list) |>
  select(trait, mean) |>
  # Add ID
  mutate(group = leaf.age)
}

durin.traitAvg.prev = trait.avg(durin, "old")
durin.traitAvg.curr = trait.avg(durin, "young")

durin.traitAvg.all = durin |>
  # Filter to just my species
  filter(species %in% c("Empetrum nigrum", "Vaccinium vitis-idaea")) |>
  # Filter to just Sogndal
  filter(siteID == "Sogndal") |>
  # Traits only
  filter(project == "Field - Traits") |>
  # Assign indivdual plant numbers
  mutate(
    # Temp code to replace missing plot nr
    DURIN_plot = replace_na(DURIN_plot, "SO_F_EN_1"),
    plantID.unique = paste0(DURIN_plot, "_plant", plant_nr)) |>
  # Tidy in long form
  select(species, habitat, DURIN_plot, plantID.unique, leaf_age, leaf_thickness_1_mm, leaf_thickness_2_mm, leaf_thickness_3_mm,
         wet_mass_g:LDMC) |>
  relocate(c(dry_mass_g, wet_mass_g, leaf_area, SLA, LDMC, leaf_thickness_1_mm:leaf_thickness_3_mm),
           .after = leaf_age) |>
  pivot_longer(cols = dry_mass_g:leaf_thickness_3_mm, names_to = "trait", values_to = "value") |>
  # Standardize traits
  mutate(trait = replace(trait,
                         trait == "leaf_thickness_1_mm" | trait == "leaf_thickness_2_mm" | trait == "leaf_thickness_3_mm",
                         "leaf_thickness")) |>
  # Remove NAs generated by errors
  drop_na(value) |>
  # Calculate averages
  group_by(DURIN_plot, species, habitat, plantID.unique, leaf_age, trait) |>
  # get_summary_stats_precise(type = "mean") |>
  summarise_all(list(~mean(.),~sd(.),
                     ~list(c(summary(.))))) %>% unnest_wider(list) |>
  select(trait, mean) |>
  mutate(group = "all")

## Calculate based on leaf age weighting ----
## Dummy data for now ##



## Join all datasets together ----
durin.traitAvg = durin.traitAvg.all |>
  bind_rows(durin.traitAvg.curr, durin.traitAvg.prev) |>
  mutate(
  group = factor(group, levels = c("young", "old", "all"),
                   labels = c("current", "previous", "both")),
  trait = factor(trait, levels = c("leaf_area", "SLA", "LDMC", "dry_mass_g", "leaf_thickness",
                                   "wet_mass_g"),
                 labels = c("Leaf area (cm^2)", "SLA (cm^2/g)", "LDMC (mg/g)", "Dry mass (g)",
                            "Leaf thickness (mm)", "Wet mass (g)")))

# Group means ----
durin.traitAvg.grp = durin.traitAvg |>
  group_by(species, trait, habitat, group) |>
  # get_summary_stats_precise(mean, type = "mean") |>
  summarise(grp.mean = mean(mean))


# Visualize ----

library(ggh4x)
library(viridis)

ggplot(durin.traitAvg, aes(x=mean, fill=group, linetype = group)) +
  geom_density(alpha=0.5, linewidth = 0.6) +
  geom_vline(data=durin.traitAvg.grp, aes(xintercept=grp.mean, color=group),
             linetype="longdash") +
  scale_fill_viridis(discrete=T) +
  scale_colour_viridis(discrete=T) +
  scale_linetype_manual(values = c("dotted", "dotted", "solid")) +
  scale_y_continuous(position = "left") +
  facet_nested(species + habitat ~ trait, scales = "free", independent = "all",
               nest_line = element_line(linetype = 2)) +
  labs(
    y="Density",
    x= "Trait value"
  ) +
  theme_classic() +
  theme(
    # legend.position="none",
    # strip.text.x = element_blank(),
    strip.background = element_blank(),
    ggh4x.facet.nestline = element_line(colour = "black"),
    axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 0.5),
    text=element_text(size=11)
  )

ggsave("visualizations/2024.04.19_TraitDensity.png", width = 10, height = 8, units = "in")
