library(rstatix)

durin = read.csv("clean_data/durin_clean.csv")

# Troubleshoot missing plots ----
durin.sogndal.missingPlot = durin |>
  # filter(siteID == "Sogndal") |>
  filter((siteID %in% c("Lygra", "Tjøtta"))) |>
  filter(project == "Field - Traits") |>
  filter(is.na(ageClass)) |>
  filter(is.na(DURIN_plot))

write.csv(durin.sogndal.missingPlot, "output/2024.04.18_LygraMissingPlot.csv")

durin.sogndal.missingPlot.count = durin |>
  filter(siteID == "Sogndal") |>
  filter(species %in% c("Empetrum nigrum", "Vaccinium vitis-idaea")) |>
  group_by(DURIN_plot) |>
  summarize(n = length(envelope_ID))

# Calculate averages ----
durin.plantAvg = durin |>
  # Filter to just my species
  filter(species %in% c("Empetrum nigrum", "Vaccinium vitis-idaea")) |>
  # Filter to just Sogndal
  filter(siteID == "Sogndal") |>
  # Traits only
  filter(project == "Field - Traits") |>
  # Assign indivdual plant numbers
  mutate(
    # Temp code to replace missing plot nr
    DURIN_plot = replace_na(DURIN_plot, "SO_F_EN_1"),
    plantID.unique = paste0(DURIN_plot, "_plant", plant_nr)) |>
  # Tidy in long form
  select(species, habitat, DURIN_plot, plantID.unique, leaf_age, leaf_thickness_1_mm, leaf_thickness_2_mm, leaf_thickness_3_mm,
         wet_mass_g:LDMC) |>
  relocate(c(dry_mass_g, wet_mass_g, leaf_area, SLA, LDMC, leaf_thickness_1_mm:leaf_thickness_3_mm),
           .after = leaf_age) |>
  pivot_longer(cols = dry_mass_g:leaf_thickness_3_mm, names_to = "trait", values_to = "value") |>
  # Standardize traits
  mutate(trait = replace(trait,
                         trait == "leaf_thickness_1_mm" | trait == "leaf_thickness_2_mm" | trait == "leaf_thickness_3_mm",
                         "leaf_thickness")) |>
  # Remove NAs generated by errors
  drop_na(value) |>
  # Calculate averages
  group_by(DURIN_plot, species, habitat, plantID.unique, leaf_age, trait) |>
  get_summary_stats(type = "mean")

# Pair plants ----
durin.plantAvgPair = durin.plantAvg |>
  # Assign random pairs
  # Wide form needed for this
  select(-c(variable, n)) |>
  pivot_wider(names_from = "trait", values_from = "mean") |>
  # Add random row numbers for sorting
  # Modified from https://stackoverflow.com/questions/15077515/random-number-generation-for-each-row
  mutate(random = runif(n())) |>
  # Assign individual plant numbers
  # Order to assign pair IDs
  select(-plantID.unique) |>
  arrange(DURIN_plot, leaf_age, random) |>
  group_by(DURIN_plot, species, habitat, leaf_age) |>
  mutate(paired = 1:n(),
         pairedID = paste0(habitat, "_", "plant", paired)) |>
  relocate(DURIN_plot, leaf_age, paired, pairedID) |>
  select(-random)

# Stats! ----
library(ggpubr)
## Test ----
durin.plantAvgPair.VV = durin.plantAvgPair |>
  filter(species == "Vaccinium vitis-idaea") |>
  ungroup() |>
  select(c(pairedID, leaf_age, habitat,LDMC:wet_mass_g)) |>
  convert_as_factor(leaf_age, habitat)


res.aov <- durin.plantAvgPair |>
  filter(species == "Vaccinium vitis-idaea") |>
  ungroup() |>
  convert_as_factor(leaf_age, habitat) |>
  select(pairedID, leaf_age,habitat, SLA) |>
  rstatix::anova_test(dv = SLA, wid = pairedID, within = c(leaf_age), between = habitat)

get_anova_table(res.aov)

res.aov <- durin.plantAvgPair |>
  filter(species == "Empetrum nigrum") |>
  ungroup() |>
  convert_as_factor(leaf_age, habitat) |>
  select(pairedID, leaf_age, habitat, leaf_thickness) |>
  rstatix::anova_test(dv = leaf_thickness, wid = pairedID, within = c(leaf_age), between = habitat)

get_anova_table(res.aov)
